---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: debian-7.6
    driver_config:
      box: chef/debian-7.6
suites:
  - name: 'default'
    run_list:
      - recipe[dotfiles]
