---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: debian-8.0
    driver_config:
      box: chef/debian-8.0
      box_url: https://downloads.sourceforge.net/project/vagrantboxjessie/debian80.box

suites:
  - name: 'default'
    run_list:
      - recipe[dotfiles]
    driver:
      customize:
        memory: 4096
