---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: debian-10
    driver:
      box: generic/debian10

suites:
  - name: 'default'
    run_list:
      - recipe[dotfiles]
    driver:
      customize:
        memory: 4096
