---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: debian-8.6
    driver:
      image: debian:8
      pid_one_command: /bin/systemd

suites:
  - name: 'default'
    run_list:
      - recipe[dotfiles]
    driver:
      customize:
        memory: 4096
