---
default_set: 'ubuntu-server-12042-x64'
sets:
  'debian-70rc1-x64-vf503':
    nodes:
      "main.foo.vm":
        prefab: 'debian-70rc1-x64-vf503'

  'ubuntu-server-12042-x64':
    nodes:
      "main.foo.vm":
        prefab: 'ubuntu-server-12042-x64'
