AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Include:
    - '**/metadata.rb'
    - '**/Gemfile'
    - '**/attributes/**/*.rb'
    - '**/libraries/**/*.rb'
    - '**/recipes/**/*.rb'
    - '**/spec/**/*.rb'
    - '**/test/**/*.rb'
    - cookbooks/**/*.rb
  Exclude:
    - berks-cookbooks/**/*
    - vendor/**/*
