AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/metadata.rb'
    - '**/Gemfile'
    - '**/attributes/**/*.rb'
    - '**/libraries/**/*.rb'
    - '**/recipes/**/*.rb'
    - '**/spec/**/*.rb'
    - '**/test/**/*.rb'
    - cookbooks/**/*.rb
  Exclude:
    - berks-cookbooks/**/*
    - vendor/**/*

Encoding:
  Exclude:
    - metadata.rb
    - Gemfile

Naming/FileName:
  Exclude:
    - Rakefile
    - Berksfile

NumericLiterals:
  Enabled: false

LineLength:
  Enabled: false

WordArray:
  MinSize: 3
