rvm:
  - 2.5
  - 2.6

before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'

install:
  - bundle install --jobs=3 --retry=3
  - BUNDLE_GEMFILE=cookbooks/dotfiles/Gemfile bundle install --jobs=3 --retry=3

script:
  - bundle exec rake
  - cd cookbooks/dotfiles && bundle exec rake
