name          'puppet-dotfiles'
version       '0.0.1'
source        'git@github.com:PierreRambaud/dotfiles.git'
author        'Pierre Rambaud (GoT)'
license       'GPLv3'
summary       'UNKNOWN'
description   'UNKNOWN'
project_page  'https://github.com/PierreRambaud/dotfiles'

dependency 'puppetlabs/stdlib'
dependency 'alup/rbenv'
dependency 'Sliim/pyenv'
