name          'puppet-dotfiles'
version       '0.0.1'
source        'UNKNOWN'
author        'Pierre Rambaud (GoT)'
license       'GPLv3'
summary       'UNKNOWN'
description   'UNKNOWN'
project_page  'UNKNOWN'

dependency 'puppetlabs/stdlib'
