#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "~/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#

xscreensaver -no-splash &
ck-launch-session &
dbus-launch &
nm-applet &
conky -c ~/.conkyrc/got &
volay &
xinput --set-prop "10" "Device Accel Constant Deceleration" 3 &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
