AllCops:
  TargetRubyVersion: 2.3
  Include:
    - metadata.rb
    - '**/Gemfile'
    - attributes/**/*
    - libraries/**/*
    - recipes/**/*
    - spec/**/*
    - test/**/*
  Exclude:
    - vendor/**/*

Encoding:
  Exclude:
    - metadata.rb
    - Gemfile

Naming/FileName:
  Exclude:
    - Rakefile
    - Berksfile

NumericLiterals:
  Enabled: false

LineLength:
  Enabled: false

WordArray:
  MinSize: 3
