AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Include:
    - metadata.rb
    - '**/Gemfile'
    - attributes/**/*
    - libraries/**/*
    - recipes/**/*
    - spec/**/*
    - test/**/*
  Exclude:
    - vendor/**/*
