source 'https://supermarket.getchef.com'

metadata

cookbook 'pyenv', git: 'https://github.com/sds/chef-pyenv.git'
cookbook 'rbenv', git: 'https://github.com/RiotGamesCookbooks/rbenv-cookbook.git'
cookbook 'ndenv', git: 'https://github.com/Numergy/ndenv-cookbook.git'
