# frozen_string_literal: true

source 'https://supermarket.getchef.com'

metadata

cookbook 'pyenv', git: 'https://github.com/sds/chef-pyenv.git'
cookbook 'ndenv', git: 'https://github.com/Numergy/ndenv-cookbook.git'
