# frozen_string_literal: true

source 'https://rubygems.org'

gem 'berkshelf'
gem 'chef', '~>13'
gem 'rack'

group :development do
  gem 'chefspec'
  gem 'foodcritic'
  gem 'kitchen-vagrant'
  gem 'rake'
  gem 'rubocop'
  gem 'serverspec'
  gem 'test-kitchen'
end
