source 'https://rubygems.org'

gem 'chef', '~>12', '<12.14'
gem 'berkshelf', '~>4'
gem 'rack', '~>1.6'

group :integration do
  gem 'rubocop'
  gem 'rake'
  gem 'test-kitchen'
  gem 'kitchen-vagrant'
  gem 'serverspec'
  gem 'chefspec'
  gem 'foodcritic'
end
