
alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias grep='grep --color=auto'

alias ll="ls -lah"

alias vi='emacs -nw'
alias vim='emacs -nw'

alias g='git'
alias gs='git status'
alias gss='git status -s'
alias gc='git commit'
alias gd='git diff'
alias gl='git log'

alias py="python"
